import bcrypt from 'bcryptjs';
import { IUser } from '../models/User';
import { ICareer } from '../models/Career';
import { IQuizQuestion } from '../models/QuizQuestion';
import { IMultimedia } from '../models/Multimedia';
import { IResource } from '../models/Resource';
import { ISuccessStory } from '../models/SuccessStory';
import { IFeedback } from '../models/Feedback';

// Pre-hashed password for password123 and admin123
const studentHashedPass = bcrypt.hashSync('password123', 10);
const adminHashedPass = bcrypt.hashSync('admin123', 10);

export const mockUsers: any[] = [
  {
    _id: '65e0a1b2c3d4e5f6a7b8c901',
    name: 'Aiden Vance',
    email: 'student@pathseeker.io',
    password: studentHashedPass,
    role: 'Student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    bio: 'Computer Science Sophomore navigating full-stack & cloud development horizons.',
    targetRole: 'Full Stack Developer',
    education: [
      {
        degree: 'B.S. in Computer Science',
        institution: 'Pacific Institute of Technology',
        fieldOfStudy: 'Software Engineering',
        startYear: '2024',
        endYear: '2028',
        grade: '3.9 GPA',
      },
    ],
    skills: ['JavaScript', 'React', 'Tailwind CSS', 'Node.js', 'Python', 'Git'],
    interests: ['Web Development', 'Artificial Intelligence', 'UI/UX Design'],
    experience: [
      {
        title: 'Frontend Development Intern',
        company: 'NovaTech Labs',
        location: 'San Francisco, CA (Remote)',
        startDate: '2025-06',
        endDate: '2025-09',
        current: false,
        description: 'Developed responsive dashboard components in React and optimized Tailwind CSS stylesheets.',
      },
    ],
    resumeUrl: '',
    resumeText: `AIDEN VANCE - Student Software Developer
Contact: student@pathseeker.io | GitHub: github.com/aidenvance | LinkedIn: linkedin.com/in/aidenvance

EDUCATION:
Pacific Institute of Technology — B.S. Computer Science (2024 - 2028), GPA: 3.9/4.0

TECHNICAL SKILLS:
Languages: TypeScript, JavaScript, Python, HTML5, CSS3, SQL
Frameworks: React, Next.js, Express, Tailwind CSS, Node.js
Tools: Git, Docker, VS Code, Figma, Postman

EXPERIENCE:
Frontend Development Intern | NovaTech Labs (Summer 2025)
- Built interactive dashboard pages using React and Tailwind CSS.
- Assisted with fixing UI responsiveness bugs across mobile viewports.
- Participated in weekly agile standup meetings.

PROJECTS:
PathSeeker Travel Tracker: Built a Next.js web application for logging milestones.
Campus Food Delivery App: Created a full-stack MERN application with Stripe payment integration.`,
    bookmarks: [
      {
        itemId: 'full-stack-developer',
        itemType: 'career',
        title: 'Full Stack Developer',
        slug: 'full-stack-developer',
        domain: 'Software Engineering',
        notes: 'Goal: Master Next.js 15 Server Actions and Docker containerization by Q3.',
        createdAt: new Date('2026-08-15'),
      },
      {
        itemId: 'ai-ml-engineer',
        itemType: 'career',
        title: 'AI & Machine Learning Engineer',
        slug: 'ai-ml-engineer',
        domain: 'Artificial Intelligence',
        notes: 'Review PyTorch fundamentals and Vector Embeddings before summer.',
        createdAt: new Date('2026-08-18'),
      },
    ],
    visaStamps: [
      {
        id: 'stamp-01',
        title: 'Inaugural Explorer Stamp',
        category: 'Onboarding',
        icon: 'FaCompass',
        tier: 'Bronze',
        unlockedAt: new Date('2026-08-10'),
        description: 'Activated PathSeeker Career Passport and established baseline profile.',
        code: 'EXP-001',
      },
      {
        id: 'stamp-02',
        title: 'Career Navigator Visa',
        category: 'Assessment',
        icon: 'FaCompassDrafting',
        tier: 'Silver',
        unlockedAt: new Date('2026-08-14'),
        description: 'Successfully completed the multi-step AI Career Aptitude Assessment.',
        code: 'NAV-204',
      },
      {
        id: 'stamp-03',
        title: 'Full Stack Voyager Pass',
        category: 'Skill Milestone',
        icon: 'FaCode',
        tier: 'Gold',
        unlockedAt: new Date('2026-08-20'),
        description: 'Mastered Full Stack Roadmap Stage 1: TypeScript & Modern Component Architecture.',
        code: 'VOY-882',
      },
    ],
    quizHistory: [
      {
        quizId: 'quiz-primary-2026',
        score: 88,
        hollandScores: {
          realistic: 65,
          investigative: 92,
          artistic: 78,
          social: 60,
          enterprising: 74,
          conventional: 55,
        },
        recommendedCareers: ['Full Stack Developer', 'AI & Machine Learning Engineer', 'Cloud Solutions Architect'],
        completedAt: new Date('2026-08-14'),
      },
    ],
    isEmailVerified: true,
  },
  {
    _id: '65e0a1b2c3d4e5f6a7b8c902',
    name: 'Elena Rostova',
    email: 'graduate@pathseeker.io',
    password: studentHashedPass,
    role: 'Graduate',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    bio: 'Recent Computer Engineering graduate seeking Junior Cloud & AI roles.',
    targetRole: 'Cloud Solutions Architect',
    education: [
      {
        degree: 'B.Eng in Computer Systems',
        institution: 'State University of Technology',
        fieldOfStudy: 'Cloud Infrastructure & Networks',
        startYear: '2021',
        endYear: '2025',
        grade: '3.8 GPA',
      },
    ],
    skills: ['AWS', 'Docker', 'Kubernetes', 'Python', 'Linux', 'Terraform', 'CI/CD'],
    interests: ['Cloud Architecture', 'DevOps Automation', 'Serverless Systems'],
    experience: [],
    resumeUrl: '',
    resumeText: '',
    bookmarks: [],
    visaStamps: [
      {
        id: 'stamp-grad-01',
        title: 'Graduate Flight Clearance',
        category: 'Degree Milestone',
        icon: 'FaGraduationCap',
        tier: 'Silver',
        unlockedAt: new Date('2026-08-01'),
        description: 'Completed Bachelor degree and commenced active job seeking voyage.',
        code: 'GRD-101',
      },
    ],
    quizHistory: [],
    isEmailVerified: true,
  },
  {
    _id: '65e0a1b2c3d4e5f6a7b8c903',
    name: 'Marcus Thorne',
    email: 'pro@pathseeker.io',
    password: studentHashedPass,
    role: 'Working Professional',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    bio: 'Mid-level Engineer pivoting into AI Engineering & Large Language Model systems.',
    targetRole: 'AI & Machine Learning Engineer',
    education: [
      {
        degree: 'B.S. Software Engineering',
        institution: 'Metro Tech University',
        fieldOfStudy: 'Computer Science',
        startYear: '2018',
        endYear: '2022',
      },
    ],
    skills: ['Python', 'PyTorch', 'TypeScript', 'PostgreSQL', 'Docker', 'FastAPI', 'LangChain'],
    interests: ['LLM Orchestration', 'Vector Databases', 'High-Performance Computing'],
    experience: [
      {
        title: 'Software Engineer II',
        company: 'Vanguard Digital Systems',
        location: 'Austin, TX',
        startDate: '2022-07',
        endDate: 'Present',
        current: true,
        description: 'Engineered microservices processing 2.4M daily transactions with 99.98% SLA.',
      },
    ],
    resumeUrl: '',
    resumeText: '',
    bookmarks: [],
    visaStamps: [
      {
        id: 'stamp-pro-01',
        title: 'Seasoned Voyager Stamp',
        category: 'Experience',
        icon: 'FaBriefcase',
        tier: 'Gold',
        unlockedAt: new Date('2026-07-15'),
        description: 'Logged 3+ years verified professional engineering flight hours.',
        code: 'VOY-900',
      },
    ],
    quizHistory: [],
    isEmailVerified: true,
  },
  {
    _id: '65e0a1b2c3d4e5f6a7b8c904',
    name: 'Director Morgan Vance',
    email: 'admin@pathseeker.io',
    password: adminHashedPass,
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    bio: 'Global Administrator for PathSeeker Career Passport Ecosystem.',
    targetRole: 'Platform Administrator',
    education: [],
    skills: ['System Administration', 'Analytics', 'Content Moderation', 'AI Governance'],
    interests: ['EdTech Innovation', 'Workforce Transformation', 'Platform Scaling'],
    experience: [],
    resumeUrl: '',
    resumeText: '',
    bookmarks: [],
    visaStamps: [
      {
        id: 'stamp-adm-01',
        title: 'Master Passport Commander',
        category: 'Authority',
        icon: 'FaCrown',
        tier: 'Platinum',
        unlockedAt: new Date('2026-01-01'),
        description: 'Full administrative sovereign access to PathSeeker global systems.',
        code: 'CMD-000',
      },
    ],
    quizHistory: [],
    isEmailVerified: true,
  },
];

export const mockCareers: any[] = [
  {
    _id: '65e0b1b2c3d4e5f6a7b8d001',
    title: 'Full Stack Developer',
    slug: 'full-stack-developer',
    domain: 'Software Engineering',
    shortDescription: 'Architect and deploy end-to-end web applications, modern interactive UIs, and resilient distributed backend APIs.',
    fullDescription: 'Full Stack Developers bridge the gap between polished user experiences and robust backend architecture. They master modern JavaScript/TypeScript ecosystems, relational and NoSQL databases, microservices, containerization, and responsive cloud deployment pipelines.',
    heroImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    salaryRange: {
      entry: 85000,
      median: 135000,
      senior: 195000,
      currency: 'USD',
    },
    jobDemand: 'Very High',
    growthRate: '+24% (2026-2032)',
    automationRisk: 14,
    futureDemandProjection: [
      { year: 2026, demandIndex: 88, avgSalary: 135000, aiImpactDescription: 'High demand for developers who can orchestrate AI components into web platforms.' },
      { year: 2028, demandIndex: 91, avgSalary: 148000, aiImpactDescription: 'Shift toward full-stack AI agents and autonomous micro-frontends.' },
      { year: 2030, demandIndex: 94, avgSalary: 164000, aiImpactDescription: 'Demand peaks for engineers managing multi-agent web systems and edge computing.' },
      { year: 2033, demandIndex: 96, avgSalary: 182000, aiImpactDescription: 'Deep specialization in real-time streaming architectures and spatial computing.' },
      { year: 2035, demandIndex: 98, avgSalary: 205000, aiImpactDescription: 'Next-gen synthesis of distributed intelligence with zero-latency interfaces.' },
    ],
    requiredSkills: [
      { name: 'TypeScript & JavaScript', level: 'Advanced', importance: 5 },
      { name: 'React / Next.js App Router', level: 'Advanced', importance: 5 },
      { name: 'Node.js & Express / NestJS', level: 'Advanced', importance: 5 },
      { name: 'MongoDB / PostgreSQL', level: 'Intermediate', importance: 4 },
      { name: 'Docker & CI/CD Pipelines', level: 'Intermediate', importance: 4 },
      { name: 'REST & GraphQL Architecture', level: 'Advanced', importance: 4 },
    ],
    dailyResponsibilities: [
      'Design and build high-performance, accessible frontend interfaces with Tailwind CSS and Framer Motion.',
      'Develop scalable RESTful and GraphQL APIs backed by MongoDB and relational databases.',
      'Implement authentication, session security, and transactional email notification systems.',
      'Write end-to-end unit and integration tests to ensure system reliability and low latency.',
      'Deploy applications to cloud environments (Vercel, AWS, GCP) using automated CI/CD workflows.',
    ],
    educationPaths: [
      'Bachelor’s degree in Computer Science, Software Engineering, or equivalent experience.',
      'Full-Stack Coding Bootcamps + demonstrable production portfolio projects.',
      'Self-taught with rigorous open-source contributions and technical certifications.',
    ],
    roadmapSteps: [
      {
        stepNumber: 1,
        title: 'Core Foundations & Modern JavaScript',
        description: 'Master ES6+ syntax, asynchronous programming (Promises, async/await), TypeScript typing, and DOM manipulation.',
        duration: '4-6 Weeks',
        resources: [
          { title: 'TypeScript Official Handbook', url: 'https://www.typescriptlang.org/docs/', type: 'Documentation' },
          { title: 'Modern JavaScript from the Beginning', url: 'https://developer.mozilla.org', type: 'Course' },
        ],
      },
      {
        stepNumber: 2,
        title: 'Frontend Mastery: React & Next.js App Router',
        description: 'Build dynamic user interfaces with state management, server components, Suspense, and responsive Tailwind styling.',
        duration: '6-8 Weeks',
        resources: [
          { title: 'Next.js App Router Learn Track', url: 'https://nextjs.org/learn', type: 'Course' },
          { title: 'Tailwind CSS Component Architecture', url: 'https://tailwindcss.com', type: 'Documentation' },
        ],
      },
      {
        stepNumber: 3,
        title: 'Backend Engineering & Database Architecture',
        description: 'Create RESTful APIs with Node.js/Express, structure Mongoose MongoDB schemas, and implement JWT role-based security.',
        duration: '6-8 Weeks',
        resources: [
          { title: 'Node.js & Mongoose Masterclass', url: 'https://nodejs.org', type: 'Course' },
          { title: 'Production API Security Guidelines', url: 'https://owasp.org', type: 'Documentation' },
        ],
      },
      {
        stepNumber: 4,
        title: 'Cloud Deployment, DevOps & Production Hardening',
        description: 'Package apps with Docker, configure CI/CD pipelines, optimize Core Web Vitals, and deploy to Vercel and AWS.',
        duration: '4-6 Weeks',
        resources: [
          { title: 'Docker for Developers', url: 'https://docker.com', type: 'Project' },
          { title: 'AWS Cloud Practitioner Guide', url: 'https://aws.amazon.com', type: 'Certification' },
        ],
      },
    ],
    voicePepTalk: 'Welcome to your Full Stack Developer voyage! You have chosen one of the most versatile and empowering disciplines in the digital world. You will have the superpower to transform an abstract concept into a living, interactive application used by thousands globally. Embrace challenges, stay curious, and build something extraordinary!',
    interviewQuestions: [
      {
        question: 'Explain how Next.js Server Components differ from Client Components and when to use each.',
        idealAnswerNotes: 'Server components run exclusively on the server, reduce client bundle size, and allow direct database/backend access without exposing secrets. Client components handle interactive state, hooks, and browser APIs.',
      },
      {
        question: 'How do you prevent SQL/NoSQL injection and maintain secure session tokens in a full-stack architecture?',
        idealAnswerNotes: 'Sanitize inputs, use parameterized queries or Mongoose ORM/ODM casting, store tokens in httpOnly secure cookies or verify signed JWT expiration with strict CORS policies.',
      },
    ],
    isTrending: true,
    isTopPick: true,
    viewsCount: 1420,
    bookmarksCount: 384,
  },
  {
    _id: '65e0b1b2c3d4e5f6a7b8d002',
    title: 'AI & Machine Learning Engineer',
    slug: 'ai-ml-engineer',
    domain: 'Artificial Intelligence',
    shortDescription: 'Train, fine-tune, and deploy foundation models, RAG pipelines, neural networks, and agentic intelligence.',
    fullDescription: 'AI and ML Engineers design the cognitive backbone of modern software. They specialize in PyTorch, Large Language Models (LLMs), retrieval-augmented generation (RAG), vector similarity search, model quantization, and production MLOps.',
    heroImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=80',
    salaryRange: {
      entry: 105000,
      median: 165000,
      senior: 240000,
      currency: 'USD',
    },
    jobDemand: 'Explosive',
    growthRate: '+38% (2026-2032)',
    automationRisk: 6,
    futureDemandProjection: [
      { year: 2026, demandIndex: 94, avgSalary: 165000, aiImpactDescription: 'Explosion of enterprise GenAI adoption and custom RAG fine-tuning.' },
      { year: 2028, demandIndex: 97, avgSalary: 188000, aiImpactDescription: 'Autonomous multi-agent orchestration becoming standard corporate infrastructure.' },
      { year: 2030, demandIndex: 99, avgSalary: 215000, aiImpactDescription: 'Multimodal neuro-symbolic systems and specialized edge AI inference.' },
      { year: 2033, demandIndex: 99, avgSalary: 245000, aiImpactDescription: 'Quantum-accelerated machine learning and synthetic biology modeling.' },
      { year: 2035, demandIndex: 99, avgSalary: 280000, aiImpactDescription: 'Pervasive cognitive computing integrated with planetary sensor networks.' },
    ],
    requiredSkills: [
      { name: 'Python & Scientific Stack (NumPy, PyTorch)', level: 'Advanced', importance: 5 },
      { name: 'Large Language Models & Prompt Engineering', level: 'Advanced', importance: 5 },
      { name: 'Retrieval Augmented Generation (RAG)', level: 'Advanced', importance: 5 },
      { name: 'Vector Databases (Pinecone, Chroma, Milvus)', level: 'Intermediate', importance: 4 },
      { name: 'Model Fine-tuning (LoRA, QLoRA)', level: 'Intermediate', importance: 4 },
      { name: 'MLOps & Triton / vLLM Deployment', level: 'Intermediate', importance: 4 },
    ],
    dailyResponsibilities: [
      'Design and deploy RAG systems with vector similarity matching and semantic re-ranking.',
      'Fine-tune open-weight models (Llama, Mistral, Gemma) for domain-specific tasks.',
      'Evaluate model hallucinations, latency metrics, and guardrail compliance.',
      'Build scalable inference microservices using FastAPI, Docker, and vLLM.',
      'Collaborate with product teams to build intuitive agentic AI workflows.',
    ],
    educationPaths: [
      'B.S. or M.S. in Computer Science, Applied Mathematics, Data Science, or AI.',
      'Applied AI Engineering specializations and published HuggingFace spaces / research.',
    ],
    roadmapSteps: [
      {
        stepNumber: 1,
        title: 'Mathematical & Python Foundations',
        description: 'Master Linear Algebra, Multivariable Calculus, Probability, and Python numerical computing with NumPy and Pandas.',
        duration: '6 Weeks',
        resources: [
          { title: 'Linear Algebra for Machine Learning', url: 'https://ocw.mit.edu', type: 'Course' },
          { title: 'Deep Learning Specialization', url: 'https://deeplearning.ai', type: 'Course' },
        ],
      },
      {
        stepNumber: 2,
        title: 'Deep Learning & Transformer Architectures',
        description: 'Implement neural networks from scratch in PyTorch, understand Attention mechanisms and self-supervised learning.',
        duration: '8 Weeks',
        resources: [
          { title: 'PyTorch Official Tutorials', url: 'https://pytorch.org/tutorials/', type: 'Documentation' },
          { title: 'Hugging Face NLP Course', url: 'https://huggingface.co/learn', type: 'Course' },
        ],
      },
      {
        stepNumber: 3,
        title: 'Production GenAI, RAG & Agents',
        description: 'Build enterprise RAG pipelines, multi-agent frameworks, function-calling tools, and vector embeddings.',
        duration: '8 Weeks',
        resources: [
          { title: 'LangChain & LlamaIndex Architecture', url: 'https://langchain.com', type: 'Documentation' },
          { title: 'Advanced RAG Systems Project', url: 'https://github.com', type: 'Project' },
        ],
      },
      {
        stepNumber: 4,
        title: 'MLOps, Quantization & Production Scaling',
        description: 'Optimize throughput with vLLM, TensorRT-LLM, model quantization (AWQ/GGUF), and monitoring pipelines.',
        duration: '6 Weeks',
        resources: [
          { title: 'MLOps Engineering on Cloud', url: 'https://cloud.google.com', type: 'Certification' },
        ],
      },
    ],
    voicePepTalk: 'Artificial Intelligence is the defining frontier of our era. By stepping into AI Engineering, you are not merely writing software—you are creating systems that think, reason, and accelerate human capability. Trust your mathematical rigor, keep experimenting, and lead the future of intelligent computing!',
    interviewQuestions: [
      {
        question: 'How do you evaluate and eliminate hallucination in production RAG systems?',
        idealAnswerNotes: 'Use RAGAS/TruLens metrics (faithfulness, answer relevance, context precision), enforce strict context grounding, implement semantic rerankers, and add hallucination detection guardrails.',
      },
      {
        question: 'Explain the difference between Full Fine-Tuning and Parameter-Efficient Fine-Tuning (PEFT/LoRA).',
        idealAnswerNotes: 'Full fine-tuning updates all model weights (computationally expensive), whereas LoRA injects low-rank trainable decomposition matrices into transformer layers, cutting memory footprint by 80% while retaining performance.',
      },
    ],
    isTrending: true,
    isTopPick: true,
    viewsCount: 2310,
    bookmarksCount: 612,
  },
  {
    _id: '65e0b1b2c3d4e5f6a7b8d003',
    title: 'Cloud Solutions Architect',
    slug: 'cloud-solutions-architect',
    domain: 'Cloud & Infrastructure',
    shortDescription: 'Design resilient, highly available multi-cloud architectures, Kubernetes clusters, and automated Terraform infrastructure.',
    fullDescription: 'Cloud Solutions Architects design the foundational infrastructure that powers enterprise software at global scale. They master AWS, GCP, Azure, Infrastructure-as-Code (Terraform), Kubernetes orchestration, zero-trust network security, and disaster recovery strategies.',
    heroImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    salaryRange: {
      entry: 100000,
      median: 155000,
      senior: 225000,
      currency: 'USD',
    },
    jobDemand: 'Very High',
    growthRate: '+26% (2026-2032)',
    automationRisk: 10,
    futureDemandProjection: [
      { year: 2026, demandIndex: 90, avgSalary: 155000, aiImpactDescription: 'Surge in hybrid-cloud AI compute cluster provisioning.' },
      { year: 2028, demandIndex: 93, avgSalary: 172000, aiImpactDescription: 'Serverless multi-region mesh architectures dominate enterprise deployments.' },
      { year: 2030, demandIndex: 95, avgSalary: 195000, aiImpactDescription: 'Autonomous self-healing infrastructure managed by AI SREs.' },
      { year: 2033, demandIndex: 97, avgSalary: 220000, aiImpactDescription: 'Zero-latency edge cloud integration across global satellite networks.' },
      { year: 2035, demandIndex: 98, avgSalary: 250000, aiImpactDescription: 'Sovereign distributed computing grids with automated energy optimization.' },
    ],
    requiredSkills: [
      { name: 'Amazon Web Services (AWS) / GCP', level: 'Advanced', importance: 5 },
      { name: 'Terraform & Infrastructure-as-Code', level: 'Advanced', importance: 5 },
      { name: 'Kubernetes & Docker Containerization', level: 'Advanced', importance: 5 },
      { name: 'Networking (VPC, BGP, Subnets, DNS)', level: 'Intermediate', importance: 4 },
      { name: 'Cloud Security & IAM Governance', level: 'Advanced', importance: 5 },
      { name: 'Cost Optimization (FinOps)', level: 'Intermediate', importance: 4 },
    ],
    dailyResponsibilities: [
      'Architect highly available, fault-tolerant infrastructure topologies across AWS and GCP.',
      'Author modular Terraform code to automate provisioning of VPCs, EKS clusters, and databases.',
      'Enforce zero-trust security postures, IAM policies, and encrypted storage baselines.',
      'Lead migration initiatives from legacy on-premises servers to cloud-native microservices.',
      'Conduct architecture reviews and optimize cloud spend through FinOps strategies.',
    ],
    educationPaths: [
      'B.S. in Information Systems, Computer Engineering, or IT.',
      'AWS Solutions Architect Professional or Google Professional Cloud Architect Certifications.',
    ],
    roadmapSteps: [
      {
        stepNumber: 1,
        title: 'Linux Systems & Networking Foundations',
        description: 'Master bash scripting, TCP/IP, DNS, SSL/TLS certificates, load balancing, and Linux server administration.',
        duration: '4-6 Weeks',
        resources: [
          { title: 'Linux Command Line Bible', url: 'https://linux.org', type: 'Documentation' },
          { title: 'Computer Networking: A Top-Down Approach', url: 'https://pearson.com', type: 'Course' },
        ],
      },
      {
        stepNumber: 2,
        title: 'Core Cloud Provider Services (AWS / GCP)',
        description: 'Deploy compute (EC2/Lambda), storage (S3), databases (RDS/DynamoDB), and VPC networking.',
        duration: '8 Weeks',
        resources: [
          { title: 'AWS Solutions Architect Associate Preparation', url: 'https://aws.amazon.com/certification/', type: 'Certification' },
        ],
      },
      {
        stepNumber: 3,
        title: 'Terraform & Infrastructure as Code (IaC)',
        description: 'Write declarative, reusable Terraform modules with state management and automated CI/CD validation.',
        duration: '6 Weeks',
        resources: [
          { title: 'HashiCorp Terraform Associate Guide', url: 'https://developer.hashicorp.com/terraform', type: 'Documentation' },
        ],
      },
      {
        stepNumber: 4,
        title: 'Kubernetes & Enterprise High Availability',
        description: 'Deploy production Kubernetes (EKS/GKE), configure Helm charts, ingress controllers, and service meshes (Istio).',
        duration: '8 Weeks',
        resources: [
          { title: 'Certified Kubernetes Administrator (CKA)', url: 'https://cncf.io', type: 'Certification' },
        ],
      },
    ],
    voicePepTalk: 'As a Cloud Solutions Architect, you are the master builder of cyberspace. You design the bridges, highways, and fortresses that allow modern business to operate seamlessly across the globe. Take pride in rock-solid uptime and robust security!',
    interviewQuestions: [
      {
        question: 'How do you design a multi-region disaster recovery architecture with RPO < 5 minutes and RTO < 15 minutes?',
        idealAnswerNotes: 'Describe active-active or warm-standby multi-region deployment using Route 53 latency routing, Aurora Global Database asynchronous replication, and automated Terraform failover scripts.',
      },
    ],
    isTrending: false,
    isTopPick: true,
    viewsCount: 980,
    bookmarksCount: 245,
  },
  {
    _id: '65e0b1b2c3d4e5f6a7b8d004',
    title: 'Product Designer (UI/UX)',
    slug: 'product-designer-ui-ux',
    domain: 'Product & Design',
    shortDescription: 'Craft intuitive, accessible, and delightful digital user experiences, design systems, and interaction workflows.',
    fullDescription: 'Product Designers merge human empathy with aesthetic excellence and business strategy. They conduct user research, create design systems in Figma, build interactive prototypes, validate usability, and ensure accessibility standards (WCAG 2.2).',
    heroImage: 'https://images.unsplash.com/photo-1581291518655-9523c932edcf?w=800&auto=format&fit=crop&q=80',
    salaryRange: {
      entry: 78000,
      median: 125000,
      senior: 180000,
      currency: 'USD',
    },
    jobDemand: 'High',
    growthRate: '+19% (2026-2032)',
    automationRisk: 12,
    futureDemandProjection: [
      { year: 2026, demandIndex: 85, avgSalary: 125000, aiImpactDescription: 'High focus on designing for generative AI interfaces and multimodal prompt UX.' },
      { year: 2028, demandIndex: 88, avgSalary: 138000, aiImpactDescription: 'Spatial computing UX for VisionOS and AR glasses takes center stage.' },
      { year: 2030, demandIndex: 91, avgSalary: 152000, aiImpactDescription: 'Adaptive AI-personalized interfaces that redesign themselves in real-time.' },
      { year: 2033, demandIndex: 93, avgSalary: 168000, aiImpactDescription: 'Haptic and brain-computer interface design paradigms.' },
      { year: 2035, demandIndex: 95, avgSalary: 188000, aiImpactDescription: 'Autonomous sensory immersion architecture.' },
    ],
    requiredSkills: [
      { name: 'Figma & Advanced Prototyping', level: 'Advanced', importance: 5 },
      { name: 'Design Systems & Component Tokens', level: 'Advanced', importance: 5 },
      { name: 'User Research & Usability Testing', level: 'Intermediate', importance: 4 },
      { name: 'Accessibility (WCAG AA/AAA)', level: 'Advanced', importance: 4 },
      { name: 'Interaction Design & Micro-animations', level: 'Intermediate', importance: 4 },
      { name: 'Basic HTML/CSS/Tailwind Understanding', level: 'Intermediate', importance: 3 },
    ],
    dailyResponsibilities: [
      'Conduct customer discovery interviews and synthesize user journey maps.',
      'Maintain and expand scalable Design Systems in Figma with variables and component tokens.',
      'Create high-fidelity interactive prototypes for stakeholder alignment and user testing.',
      'Collaborate directly with frontend engineers during sprint design reviews and QA.',
      'Ensure all interfaces conform to accessibility standards and internationalization norms.',
    ],
    educationPaths: [
      'B.A. or B.S. in Graphic Design, HCI, Interactive Media, or self-directed portfolio.',
      'Polished Case Studies demonstrating end-to-end problem discovery, iteration, and measurable business outcomes.',
    ],
    roadmapSteps: [
      {
        stepNumber: 1,
        title: 'Design Principles & Visual Hierarchy',
        description: 'Master typography, spacing grids, color theory, contrast ratios, and visual balance.',
        duration: '4 Weeks',
        resources: [
          { title: 'Refactoring UI Guide', url: 'https://refactoringui.com', type: 'Course' },
        ],
      },
      {
        stepNumber: 2,
        title: 'Figma & Design Systems Mastery',
        description: 'Build enterprise component libraries with auto-layout, variants, design tokens, and interactive component states.',
        duration: '6 Weeks',
        resources: [
          { title: 'Figma Official Design Systems Track', url: 'https://figma.com/learn', type: 'Documentation' },
        ],
      },
      {
        stepNumber: 3,
        title: 'User Research, Wireframing & Usability Testing',
        description: 'Formulate hypotheses, execute unmoderated usability tests, analyze heatmaps, and iterate based on quantitative data.',
        duration: '6 Weeks',
        resources: [
          { title: 'Nielsen Norman Group UX Research Methods', url: 'https://nngroup.com', type: 'Documentation' },
        ],
      },
    ],
    voicePepTalk: 'Every great software experience starts with empathy. As a Product Designer, you are the user advocate and visionary artist who makes complex digital tools intuitive, elegant, and empowering. Design with purpose and craft interfaces that inspire!',
    interviewQuestions: [
      {
        question: 'Walk me through how you establish design system tokens that harmonize between Figma and Tailwind CSS.',
        idealAnswerNotes: 'Explain setting semantic color/spacing tokens in Figma variables, syncing them via Style Dictionary or JSON exports, and mapping them directly to tailwind.config.js theme extensions.',
      },
    ],
    isTrending: false,
    isTopPick: false,
    viewsCount: 750,
    bookmarksCount: 190,
  },
  {
    _id: '65e0b1b2c3d4e5f6a7b8d005',
    title: 'Cybersecurity Analyst',
    slug: 'cybersecurity-analyst',
    domain: 'Security & Intelligence',
    shortDescription: 'Defend organizational assets against advanced threats, execute penetration tests, and manage incident response.',
    fullDescription: 'Cybersecurity Analysts protect networks, cloud infrastructure, and sensitive data from cyber attacks. They monitor SIEM alerts, perform vulnerability scans, execute red-team penetration tests, configure firewalls, and respond to critical zero-day incidents.',
    heroImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=80',
    salaryRange: {
      entry: 82000,
      median: 130000,
      senior: 190000,
      currency: 'USD',
    },
    jobDemand: 'Very High',
    growthRate: '+32% (2026-2032)',
    automationRisk: 9,
    futureDemandProjection: [
      { year: 2026, demandIndex: 91, avgSalary: 130000, aiImpactDescription: 'Defense against AI-generated phishing and autonomous malware agents.' },
      { year: 2028, demandIndex: 94, avgSalary: 146000, aiImpactDescription: 'Zero-trust architecture mandated across all corporate networks.' },
      { year: 2030, demandIndex: 96, avgSalary: 168000, aiImpactDescription: 'Post-quantum cryptographic migration for critical infrastructure.' },
      { year: 2033, demandIndex: 98, avgSalary: 192000, aiImpactDescription: 'AI-automated SOC defense grids operating at microsecond response intervals.' },
      { year: 2035, demandIndex: 99, avgSalary: 220000, aiImpactDescription: 'Planetary sovereign cyber defense and autonomous threat neutralization.' },
    ],
    requiredSkills: [
      { name: 'Security Operations & SIEM (Splunk/Sentinel)', level: 'Advanced', importance: 5 },
      { name: 'Threat Hunting & Incident Response', level: 'Advanced', importance: 5 },
      { name: 'Network Security (Wireshark, Firewalls)', level: 'Intermediate', importance: 4 },
      { name: 'Penetration Testing & OWASP Top 10', level: 'Intermediate', importance: 4 },
      { name: 'Cloud Security (AWS/Azure IAM)', level: 'Intermediate', importance: 4 },
    ],
    dailyResponsibilities: [
      'Monitor and triage real-time alerts from SIEM tools and endpoint detection systems.',
      'Investigate suspicious network traffic, malware payloads, and phishing campaigns.',
      'Execute regular vulnerability scans and coordinate patching with DevOps engineers.',
      'Formulate incident response runbooks and conduct simulated tabletop breach drills.',
      'Audit access controls to enforce principle of least privilege.',
    ],
    educationPaths: [
      'B.S. in Cybersecurity, Information Assurance, or Computer Science.',
      'CompTIA Security+, Certified Ethical Hacker (CEH), or CISSP credentials.',
    ],
    roadmapSteps: [
      {
        stepNumber: 1,
        title: 'Security Fundamentals & Networking',
        description: 'Understand TCP/IP, OSI model, packet analysis with Wireshark, cryptography basics, and threat terminology.',
        duration: '6 Weeks',
        resources: [
          { title: 'CompTIA Security+ SY0-701 Prep', url: 'https://comptia.org', type: 'Certification' },
        ],
      },
      {
        stepNumber: 2,
        title: 'SIEM, Threat Analysis & Log Forensics',
        description: 'Ingest and analyze logs in Splunk and Microsoft Sentinel, write detection rules, and track APT attack matrices.',
        duration: '8 Weeks',
        resources: [
          { title: 'MITRE ATT&CK Framework Documentation', url: 'https://attack.mitre.org', type: 'Documentation' },
        ],
      },
    ],
    voicePepTalk: 'In a world driven by digital networks, Cybersecurity professionals are the vital guardians standing between chaos and digital trust. Your sharp eye and technical discipline protect hospitals, financial systems, and human privacy. Defend with excellence!',
    interviewQuestions: [
      {
        question: 'Explain how you would contain a suspected ransomware infection spreading across an internal subnet.',
        idealAnswerNotes: 'Immediately isolate affected hosts at the switch/EDR level, preserve memory dumps for forensic analysis, disable compromised service accounts, and verify immutable backups before recovery.',
      },
    ],
    isTrending: true,
    isTopPick: false,
    viewsCount: 1100,
    bookmarksCount: 310,
  },
];

export const mockQuizQuestions: any[] = [
  {
    _id: '65e0c1b2c3d4e5f6a7b8e001',
    questionText: 'I enjoy architecting technical systems, writing code, and solving complex algorithmic challenges.',
    category: 'Investigative',
    questionType: 'likert',
    weight: 2,
    timeLimitSeconds: 25,
    sliderMinLabel: 'Strongly Disagree',
    sliderMaxLabel: 'Strongly Agree',
    options: [
      { label: 'Strongly Disagree', scoreValue: 1, associatedDomains: ['Design', 'Social'] },
      { label: 'Disagree', scoreValue: 2, associatedDomains: ['Product'] },
      { label: 'Neutral', scoreValue: 3, associatedDomains: [] },
      { label: 'Agree', scoreValue: 4, associatedDomains: ['Software Engineering', 'Cloud'] },
      { label: 'Strongly Agree', scoreValue: 5, associatedDomains: ['Software Engineering', 'Artificial Intelligence'] },
    ],
    order: 1,
  },
  {
    _id: '65e0c1b2c3d4e5f6a7b8e002',
    questionText: 'How strongly do you prefer working with visual aesthetics, user interaction flows, and interface typography?',
    category: 'Artistic',
    questionType: 'slider',
    weight: 2,
    timeLimitSeconds: 30,
    sliderMinLabel: 'Purely Backend / Data Focused (0)',
    sliderMaxLabel: 'Obsessed with Visual Craft & UX (100)',
    options: [
      { label: 'Low Preference for Visual Design', scoreValue: 20, associatedDomains: ['Cloud & Infrastructure', 'Security'] },
      { label: 'Balanced Interest', scoreValue: 50, associatedDomains: ['Software Engineering'] },
      { label: 'High Passion for Design & Interaction', scoreValue: 90, associatedDomains: ['Product & Design'] },
    ],
    order: 2,
  },
  {
    _id: '65e0c1b2c3d4e5f6a7b8e003',
    questionText: 'When a critical system goes down at 2 AM, which reaction best matches your instinctive mindset?',
    category: 'Realistic',
    questionType: 'timed_choice',
    weight: 3,
    timeLimitSeconds: 20,
    options: [
      { label: 'Dive straight into server logs, network packet traces, and isolate root-cause latency', scoreValue: 5, associatedDomains: ['Cloud & Infrastructure', 'Security & Intelligence'] },
      { label: 'Review git commits and patch the broken frontend component or API route', scoreValue: 4, associatedDomains: ['Software Engineering'] },
      { label: 'Communicate with stakeholders and formulate user status page updates', scoreValue: 3, associatedDomains: ['Product & Design', 'Management'] },
      { label: 'Run diagnostic test scripts and verify model output telemetry', scoreValue: 5, associatedDomains: ['Artificial Intelligence'] },
    ],
    order: 3,
  },
  {
    _id: '65e0c1b2c3d4e5f6a7b8e004',
    questionText: 'I am fascinated by machine learning models, statistical patterns, and building autonomous AI assistants.',
    category: 'Tech-Aptitude',
    questionType: 'likert',
    weight: 3,
    timeLimitSeconds: 25,
    sliderMinLabel: 'Not Interested',
    sliderMaxLabel: 'Extremely Passionate',
    options: [
      { label: 'Strongly Disagree', scoreValue: 1, associatedDomains: [] },
      { label: 'Disagree', scoreValue: 2, associatedDomains: [] },
      { label: 'Neutral', scoreValue: 3, associatedDomains: [] },
      { label: 'Agree', scoreValue: 4, associatedDomains: ['Artificial Intelligence'] },
      { label: 'Strongly Agree', scoreValue: 5, associatedDomains: ['Artificial Intelligence', 'Software Engineering'] },
    ],
    order: 4,
  },
  {
    _id: '65e0c1b2c3d4e5f6a7b8e005',
    questionText: 'I prioritize defending digital privacy, discovering software vulnerabilities, and analyzing cyber threats.',
    category: 'Investigative',
    questionType: 'likert',
    weight: 2,
    timeLimitSeconds: 25,
    sliderMinLabel: 'Least Preferred',
    sliderMaxLabel: 'Most Preferred',
    options: [
      { label: 'Strongly Disagree', scoreValue: 1, associatedDomains: [] },
      { label: 'Disagree', scoreValue: 2, associatedDomains: [] },
      { label: 'Neutral', scoreValue: 3, associatedDomains: [] },
      { label: 'Agree', scoreValue: 4, associatedDomains: ['Security & Intelligence'] },
      { label: 'Strongly Agree', scoreValue: 5, associatedDomains: ['Security & Intelligence', 'Cloud & Infrastructure'] },
    ],
    order: 5,
  },
];

export const mockMultimedia: any[] = [
  {
    _id: '65e0d1b2c3d4e5f6a7b8f001',
    title: 'A Day in the Life of a Senior Full Stack Engineer at a Fast-Growing Tech Unicorn',
    slug: 'day-in-life-senior-full-stack-engineer',
    type: 'video',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80',
    duration: '12:45',
    category: 'Day in the Life',
    speakerName: 'Sarah Lin',
    speakerRole: 'Staff Software Engineer @ ScaleVelocity',
    speakerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    description: 'Go behind the scenes with Sarah as she conducts architecture reviews, pairs on Next.js frontend performance optimizations, and deploys high-scale microservices to production.',
    transcript: [
      { timestamp: '00:00', speaker: 'Sarah Lin', text: 'Good morning everyone! Welcome to a Tuesday in my life as a Staff Full Stack Engineer.' },
      { timestamp: '02:15', speaker: 'Sarah Lin', text: 'First thing at 9:30 AM is our distributed architecture standup. We are reviewing server-rendered cache invalidation.' },
      { timestamp: '05:40', speaker: 'Sarah Lin', text: 'Now we are diving deep into optimizing Core Web Vitals for our dashboard. We reduced First Contentful Paint by 40%.' },
      { timestamp: '09:10', speaker: 'Sarah Lin', text: 'After lunch, I mentor junior developers on TypeScript generics and error boundaries in React.' },
      { timestamp: '12:00', speaker: 'Sarah Lin', text: 'Wrapping up the day with our automated CI/CD canary release. Thanks for watching!' },
    ],
    tags: ['Full Stack', 'Career Advice', 'React', 'Next.js', 'Engineering Culture'],
    ratings: [
      {
        user: '65e0a1b2c3d4e5f6a7b8c901',
        userName: 'Aiden Vance',
        rating: 5,
        comment: 'Incredible breakdown of real-world responsibilities and daily engineering cadence!',
        createdAt: new Date('2026-08-16'),
      },
    ],
    averageRating: 4.9,
    totalReviews: 18,
    thumbsUpCount: 142,
    thumbsDownCount: 3,
    isFeatured: true,
    viewsCount: 2450,
  },
  {
    _id: '65e0d1b2c3d4e5f6a7b8f002',
    title: 'Masterclass: Transitioning from Traditional Backend to AI & Machine Learning Engineering',
    slug: 'masterclass-backend-to-ai-engineer',
    type: 'audio',
    mediaUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    embedUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80',
    duration: '28:10',
    category: 'Masterclass',
    speakerName: 'Dr. Aris Thorne',
    speakerRole: 'AI Research Director @ NeuralMatrix',
    speakerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    description: 'An in-depth audio masterclass on the exact math prerequisites, PyTorch mental models, and RAG architecture principles needed to successfully pivot into modern AI engineering.',
    transcript: [
      { timestamp: '00:00', speaker: 'Dr. Aris Thorne', text: 'Welcome to this masterclass on bridging the gap from backend systems to AI engineering.' },
      { timestamp: '04:20', speaker: 'Dr. Aris Thorne', text: 'The biggest misconception is that you need a PhD in pure math. What you really need is intuition for vector spaces and tensors.' },
      { timestamp: '12:45', speaker: 'Dr. Aris Thorne', text: 'Let us discuss RAG architecture: embedding generation, chunking strategies, and hybrid vector search.' },
      { timestamp: '22:15', speaker: 'Dr. Aris Thorne', text: 'My #1 recommendation: Build and deploy one end-to-end LLM application on GitHub with live inference.' },
    ],
    tags: ['AI Engineering', 'Machine Learning', 'Podcast', 'Career Pivot', 'PyTorch'],
    ratings: [],
    averageRating: 4.8,
    totalReviews: 12,
    thumbsUpCount: 98,
    thumbsDownCount: 1,
    isFeatured: true,
    viewsCount: 1820,
  },
];

export const mockResources: any[] = [
  {
    _id: '65e0e1b2c3d4e5f6a7b8a001',
    title: 'The Ultimate Full-Stack Developer 2026 Flight Checklist & Roadmap',
    slug: 'full-stack-developer-2026-flight-checklist',
    description: 'A comprehensive 6-page printable guide and audit checklist containing essential technologies, repository templates, and milestone markers for full-stack mastery.',
    category: 'Career Guides',
    targetAudience: 'Student',
    format: 'PDF',
    fileUrl: '/downloads/full-stack-roadmap-2026.pdf',
    previewSnippet: 'Section 1: Modern TypeScript Fundamentals\nSection 2: Next.js 15 Server Components & Server Actions\nSection 3: Mongoose Indexing & Security Hardening\nSection 4: Production CI/CD & Dockerization Checkpoints',
    pagesCount: 6,
    fileSize: '2.4 MB',
    downloadCount: 342,
    tags: ['Full Stack', 'Roadmap', 'TypeScript', 'Next.js', 'Checklist'],
    isFeatured: true,
  },
  {
    _id: '65e0e1b2c3d4e5f6a7b8a002',
    title: 'FAANG-Ready System Design & Technical Interview Cheatsheet',
    slug: 'system-design-interview-cheatsheet',
    description: 'Quick-reference diagrams, latency numbers every engineer should know, CAP theorem trade-offs, and microservice communication patterns for technical interviews.',
    category: 'Interview Cheatsheets',
    targetAudience: 'Graduate',
    format: 'Cheatsheet',
    fileUrl: '/downloads/system-design-cheatsheet.pdf',
    previewSnippet: 'Latency Numbers: L1 Cache: 0.5 ns | RAM: 100 ns | SSD Read: 16 µs | Network roundtrip CA to Netherlands: 150 ms\nKey Design Patterns: CQRS, Event Sourcing, Circuit Breaker, Saga Pattern',
    pagesCount: 4,
    fileSize: '1.6 MB',
    downloadCount: 512,
    tags: ['System Design', 'Interview', 'Architecture', 'FAANG'],
    isFeatured: true,
  },
  {
    _id: '65e0e1b2c3d4e5f6a7b8a003',
    title: '2026 Global Tech Salary & Compensation Benchmark Infographic',
    slug: 'tech-salary-benchmark-infographic-2026',
    description: 'Visual high-resolution infographic summarizing percentile salary bands, equity packages, and remote wage trends across 15 engineering disciplines.',
    category: 'Salary Benchmark',
    targetAudience: 'Working Professional',
    format: 'Infographic',
    fileUrl: '/downloads/tech-salary-benchmark-2026.pdf',
    previewSnippet: 'Tier 1 Compensation: AI Engineers ($165k-$240k) | Cloud Architects ($155k-$225k) | Security Specialists ($130k-$190k)\nRemote Flexibility Index: 82% of Senior Roles support Distributed Teams',
    pagesCount: 2,
    fileSize: '3.1 MB',
    downloadCount: 678,
    tags: ['Salary', 'Compensation', 'Infographic', 'Career Growth'],
    isFeatured: true,
  },
];

export const mockSuccessStories: any[] = [
  {
    _id: '65e0f1b2c3d4e5f6a7b8b001',
    authorName: 'Maya Lin',
    authorRole: 'Full Stack Engineer',
    company: 'Stripe',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    domain: 'Software Engineering',
    currentSalary: '$145,000 / yr',
    timeToTransition: '7 Months',
    educationalPath: 'Biology graduate with zero prior programming background. Started with CS50 and self-taught TypeScript/React.',
    challenges: 'Felt severe imposter syndrome, struggled with complex async state management, and received 40 initial resume rejections.',
    breakthroughMilestones: 'Followed PathSeeker’s structured flight roadmap, earned 4 Visa Stamps, and built a full-stack open-source payment ledger app.',
    outcome: 'Landed a Full Stack Engineer offer at Stripe with a $145k base salary and remote flexibility.',
    adviceForOthers: 'Do not stay in tutorial hell. Build full-stack projects with real authentication and databases, then deploy them for public users!',
    status: 'approved',
    likesCount: 84,
  },
  {
    _id: '65e0f1b2c3d4e5f6a7b8b002',
    authorName: 'Carlos Mendoza',
    authorRole: 'Cloud Solutions Architect',
    company: 'Amazon Web Services (AWS)',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    domain: 'Cloud & Infrastructure',
    currentSalary: '$175,000 / yr',
    timeToTransition: '9 Months',
    educationalPath: 'Worked as an IT Helpdesk technician for 4 years before embarking on the Cloud Architecture voyage.',
    challenges: 'Learning Terraform and container networking while working 40 hours a week on helpdesk tickets.',
    breakthroughMilestones: 'Earned the AWS Solutions Architect and CKA credentials, followed by creating automated multi-region disaster recovery templates.',
    outcome: 'Hired directly into AWS Professional Services as a Solutions Architect.',
    adviceForOthers: 'Terraform is the universal language of modern infrastructure. Automate everything and document your architectural decisions.',
    status: 'approved',
    likesCount: 112,
  },
];

export const mockFeedback: any[] = [
  {
    _id: '65e001b2c3d4e5f6a7b8c001',
    userName: 'Aiden Vance',
    userEmail: 'student@pathseeker.io',
    category: 'Feature Suggestion',
    message: 'I love the Career Passport visa stamps! Could we also have an exportable LinkedIn badge for completed flight paths?',
    priority: 'Medium',
    sentiment: 'Positive',
    status: 'In Progress',
    adminNotes: 'Great idea. Slated for Career Passport Phase 2 badge sharing.',
    createdAt: new Date('2026-08-20'),
  },
  {
    _id: '65e001b2c3d4e5f6a7b8c002',
    userName: 'Elena Rostova',
    userEmail: 'graduate@pathseeker.io',
    category: 'Career Query',
    message: 'Are there plans to add Quantum Computing and Robotics specialization roadmaps to the Career Bank?',
    priority: 'Low',
    sentiment: 'Neutral',
    status: 'New',
    adminNotes: 'Under curriculum review with faculty partners.',
    createdAt: new Date('2026-08-22'),
  },
];

export const mockNotifications: any[] = [
  {
    _id: '65e002b2c3d4e5f6a7b8d001',
    user: '65e0a1b2c3d4e5f6a7b8c901',
    title: 'Visa Stamp Awarded! 🧭',
    message: 'You unlocked the Full Stack Voyager Pass (Gold Tier) on your Career Passport.',
    type: 'visa_stamp',
    isRead: false,
    actionUrl: '/profile',
    createdAt: new Date('2026-08-20'),
  },
  {
    _id: '65e002b2c3d4e5f6a7b8d002',
    user: '65e0a1b2c3d4e5f6a7b8c901',
    title: 'New Multimedia Masterclass Published',
    message: 'Dr. Aris Thorne released "Backend to AI Engineering Masterclass". Check it out!',
    type: 'system',
    isRead: true,
    actionUrl: '/multimedia',
    createdAt: new Date('2026-08-18'),
  },
];
